//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPERP2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catFactory
    {
        public catFactory()
        {
            this.Factories = new HashSet<Factory>();
        }
    
        public int Id { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual ICollection<Factory> Factories { get; set; }
    }
}
