//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPERP2015.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPModelContainer : DbContext
    {
        public ERPModelContainer()
            : base("name=ERPModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<catCurrency> catCurrencies { get; set; }
        public virtual DbSet<catCustomer> catCustomers { get; set; }
        public virtual DbSet<catFactory> catFactories { get; set; }
        public virtual DbSet<catPay> catPays { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Factory> Factories { get; set; }
        public virtual DbSet<typeFactory> typeFactories { get; set; }
        public virtual DbSet<typeCustomer> typeCustomers { get; set; }
    }
}
